# Default variables for Sysmon role
sysmon_config_url: "https://raw.githubusercontent.com/SwiftOnSecurity/sysmon-config/master/sysmonconfig-export.xml"
sysmon_binary_url: "https://download.sysinternals.com/files/Sysmon.zip"
